Lint/Eval:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/LineLength:
  Max: 140
Metrics/MethodLength:
  Max: 25
Style/BracesAroundHashParameters:
  Enabled: false
Style/Documentation:
  Enabled: false
