Lint/Eval:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 11
Style/BracesAroundHashParameters:
  Enabled: false
Style/Documentation:
  Enabled: false
